### ISSUE TITLE
arms 插件 使用 request()报错

### ISSUE THREAD

**Issue by sunsgneayo** [webman-php/arms#1]
Error: Call to a member function tag() on null in /var/www/php/fj-dmp/vendor/webman/arms/src/Arms.php:43

request()->rootSpan->tag('db.statement', $query->sql . " /{$query->time}ms/");

阿里云还是收到了调用链

**Comment by walkor** [comment]
https://github.com/webman-php/arms/blob/main/src/Arms.php
更新主干代码试下，没问题的话我再发版本

**Comment by sunsgneayo** [comment]
我是这样改的 
if (class_exists('\Illuminate\Database\Events\QueryExecuted')) {
                $rootSpan = $tracer->newTrace();
                Db::listen(function (\Illuminate\Database\Events\QueryExecuted $query) use ($rootSpan) {
                    $rootSpan->tag('db.statement', $query->sql . " /*{$query->time}ms*/");
//                    var_dump($query->sql , $query->time);
//                    \request();
//                    request()->rootSpan->tag('db.statement', $query->sql . " /*{$query->time}ms*/");
                });
            }

用newTrace() 有什么影响呢，

**Comment by walkor** [comment]
没仔细研究过，不清楚
